source :rubygems
source "http://rubygems.org"
source :rubyforge
source "http://gems.rubyforge.org"
source :gemcutter
source "http://gemcutter.org"

gem "sinatra"
gem "heroku"
gem "rb-readline"
gem "bootstrap"
gem "haml"
gem "sinatra-authentication"
gem "activerecord"
gem "sinatra-activerecord"
gem "rack"
gem "activerecord-postgresql-adapter"
gem "rake"
gem "pg"
gem "excon"
gem "json"
